name=Saved by the Totem
desc=You can be saved by the Totem.
author=iAngel
# Set this to True only if your mod customizes anything that is loaded before starting a game, like the main menu or loading screens.
requires reload=True
tags = Sounds, Models, Items
